/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Control_Reg_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "Pin_7_aliases.h"
#include "Pin_7.h"
#include "Pin_8_aliases.h"
#include "Pin_8.h"
#include "UART_1.h"
#include "ADC_SAR_1.h"
#include "ADC_SAR_2.h"
#include "B1_aliases.h"
#include "B1.h"
#include "B2_aliases.h"
#include "B2.h"
#include "B3_aliases.h"
#include "B3.h"
#include "B4_aliases.h"
#include "B4.h"
#include "VRy_aliases.h"
#include "VRy.h"
#include "VRx_aliases.h"
#include "VRx.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

