# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\ologa\Documents\MIT\Senior S22\6.1151\Final Project\vga.cydsn\vga.cyprj
# Date: Wed, 04 May 2022 03:26:41 GMT
#set_units -time ns
create_clock -name {CyXTAL} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/xtal}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 15.350877192982454 -waveform {0 7.67543859649123} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 15.350877192982454 -waveform {0 7.67543859649123} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {VGA_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 17} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {UART_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 425 849} -nominal_period 6508.77192982456 [list [get_pins {ClockBlock/dclk_glb_1}]]


# Component constraints for C:\Users\ologa\Documents\MIT\Senior S22\6.1151\Final Project\vga.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\ologa\Documents\MIT\Senior S22\6.1151\Final Project\vga.cydsn\vga.cyprj
# Date: Wed, 04 May 2022 03:26:36 GMT
